name: Go
on:
  push:
    tags:
      - 0.*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: 
        sudo apt-get update
        sudo apt install gcc-x86-64-windows-gnu
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o wb.exe -v main.go        

